---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/vertx.svg"
  labels:
    project: "movietickets"
    provider: "fabric8"
    version: "1.0-SNAPSHOT"
    group: "paytm"
  name: "movietickets"
spec:
  ports:
  - port: 8778
    protocol: "TCP"
    targetPort: 8778
  selector:
    project: "movietickets"
    provider: "fabric8"
    group: "paytm"
  type: "LoadBalancer"
