---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      fabric8.io/iconUrl: "img/icons/vertx.svg"
    labels:
      project: "movietickets"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "paytm"
    name: "movietickets"
  spec:
    ports:
    - port: 8778
      protocol: "TCP"
      targetPort: 8778
    selector:
      project: "movietickets"
      provider: "fabric8"
      group: "paytm"
    type: "LoadBalancer"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/vertx.svg"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=movietickets&var-version=1.0-SNAPSHOT"
    labels:
      project: "movietickets"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "paytm"
    name: "movietickets"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "movietickets"
        provider: "fabric8"
        group: "paytm"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/vertx.svg"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=movietickets&var-version=1.0-SNAPSHOT"
        labels:
          project: "movietickets"
          provider: "fabric8"
          version: "1.0-SNAPSHOT"
          group: "paytm"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "paytm/movietickets:latest"
          imagePullPolicy: "IfNotPresent"
          name: "javaapp"
          ports:
          - containerPort: 9779
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          securityContext:
            privileged: false
kind: "List"
